version: '2'
services:
  grafana_graphite:
    build: .
    image: graphite-statsd-influxdb
    container_name: graphite-statsd-influxdb
    ports:
      - '80:80'
      - '81:81'
      - '2003:2003'
      - '8125:8125/udp'
      - '8126:8126'
      - '8086:8086'
      - '8083:8083'
    volumes:
      - ./docker-share/data/whisper:/opt/graphite/storage/whisper
      - ./docker-share/data/grafana:/opt/grafana/data
      - ./docker-share/log/graphite:/opt/graphite/storage/log
      - ./docker-share/influxdb:/var/lib/influxdb
